### ISSUE TITLE
Missing the GraphQl plugins & derivers ?

### ISSUE THREAD

**Issue by yched** [drupal-graphql/graphql-views#1]
The module just contains the Views plugins for the GraphQL display, but the corresponding GraphQL plugins that actiually give it some behavior in the schema haven't been added back after https://github.com/drupal-graphql/graphql/pull/411

So you can add a GraphQL display to a view, but it just does nothing :-)

**Comment by fubhy** [comment]
Yeah. We are currently still working on the main module so these haven't gotten a lot of attention lately.

**Comment by fubhy** [comment]
I've re-added the plugins.
