### ISSUE TITLE
Crashes when rendering fields

### ISSUE THREAD

**Issue by gheydon** [drupal-graphql/graphql-views#29]
When displaying fields you cannot render fields you will get the following error.

`NOTICE: PHP message: Uncaught PHP Exception LogicException: "Render context is empty, because render() was called outside of a renderRoot() or renderPlain() call. Use renderPlain()/renderRoot() or #lazy_builder/#pre_render instead.`

ATM I need to display these as raw values to avoid crashing.

**Comment by pmelab** [comment]
Fields are currently not supported. Probably views display plugin should enforce that.
